---
driver:
  name: ec2

driver_config:
  aws_ssh_key_id: chef-kitchen-test-aws
  instance_type: t2.medium

transport:
  username: <%= ENV['AWS_KITCHEN_USER'] %>

provisioner:
  name: chef_zero
  data_path: ../../pkg/

platforms:
  - name: aws
    driver:
      image_id: <%= ENV['AWS_KITCHEN_AMI_ID'] %>

suites:
  - name: default
    run_list:
      - recipe[packer_payload::default]
    attributes:
      packer_payload:
        source_path: /tmp/kitchen/data
app_version: <%= ENV['KITCHEN_APP_VERSION'] %>
